# Generated by Django 3.0.5 on 2022-01-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_shopkeeper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('shopkeeperId', models.PositiveIntegerField(null=True)),
                ('patientName', models.CharField(max_length=40, null=True)),
                ('shopkeeperName', models.CharField(max_length=40, null=True)),
                ('orderDate', models.DateField(auto_now=True)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='shopkeeper',
            name='department',
        ),
        migrations.AddField(
            model_name='shopkeeper',
            name='type',
            field=models.CharField(choices=[('Medicine', 'Medicine'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
