# Generated by Django 3.0.5 on 2022-01-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_auto_20220117_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/ShopkeeperProfilePic/'),
        ),
    ]
