# Generated by Django 3.0.5 on 2022-01-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_auto_20220118_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopkeeper',
            name='type',
            field=models.CharField(choices=[('Food', 'Food'), ('General', 'General'), ('Medicine', 'Medicine'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
