# Generated by Django 3.0.5 on 2022-01-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_auto_20220118_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='covidStatus',
            field=models.CharField(choices=[('Fully-Vaccinated', 'Fully-Vaccinated'), ('Requested Testing', 'Requested Testing'), ('Covid Positive', 'Covid Positive'), ('Quarantined', 'Quarantined'), ('Unvaccinated', 'Unvaccinated')], default='Fully Vaccinated', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologists', 'Dermatologists'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons'), ('General Physician', 'General Physician'), ('Other', 'Other')], default='Cardiologist', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='assignedDoctorId',
            field=models.PositiveIntegerField(default=-1),
        ),
    ]
