# Generated by Django 3.0.5 on 2022-01-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_auto_20220119_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(default='default.png', upload_to='profile_pic/DoctorProfilePic/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='assignedDoctorId',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.ImageField(default='images/default.png', upload_to='profile_pic/PatientProfilePic/'),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='profile_pic',
            field=models.ImageField(default='images/default.png', upload_to='profile_pic/ShopkeeperProfilePic/'),
        ),
    ]
